[package]
name = "ilia-windows"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
swayipc = "3.0.3"
anyhow.workspace = true
iced.workspace = true
iced_core.workspace = true
iced_runtime.workspace = true
